######################################################################
# Automatically generated by qmake (2.01a) Wed May 7 09:41:47 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
