######################################################################
# Automatically generated by qmake (2.01a) Wed May 28 19:07:59 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
