#include <unistd.h>
#include <GL/glew.h> 
#include <GL/gl.h>
#include <GL/freeglut.h>
#include <iostream>
#include <vector>
#include <limits.h>
#define _USE_MATH_DEFINES
#include <cmath>
#include <atomic>
#include <condition_variable>
#include <thread>
#include <pthread.h>
#include <chrono>
#include <ctime>
#include "shader.h"
#include "model.h"
#include "robot.h"
#include "plotter.h"
